{
 "title": "YTPLEN",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(api_request_duration[24h]) / avg_over_time(videos_count[24h])\n",
     "legendFormat": "__auto"
    },
    { "expr": "videos_count[24h]\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Request Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "api_request_duration[24h]" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_requests[24h]" }
   ]
  },
  {
   "title": "Videos Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "videos_count[24h]" }
   ]
  },
  {
   "title": "API Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "api_error_count[24h]", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{app=\"ytpgo\"} | json | line_format \"{{.level}} {{.msg}}\"\n"
    }
   ]
  }
 ]
}