global:
  scrape_interval: 15s  
  evaluation_interval: 15s 

scrape_configs:

  # Scrape Loki metrics
  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]  

  # Scrape application metrics
  - job_name: "ytpgo"
    static_configs:
      - targets: ['http://13.201.172.96:2112']
