name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to Droplet
      run: |
        scp -o StrictHostKeyChecking=no -r ./* root@137.184.127.9:/gpl_monitoring

    - name: Debug SSH Connection
      run: |
        ssh -v root@137.184.127.9

    - name: Deploy on Droplet
      run: |
        ssh root@137.184.127.9 'cd /gpl_monitoring && docker-compose up --build -d'
